### ISSUE TITLE
很想要一个切图下载的功能

### ISSUE THREAD

**Issue by JAKOBYU** [leadream/heron-handoff#68]

**Comment by leadream** [comment]
把标注文件传到服务器，生成一个链接就有了。
参考：https://docs.heron.design/designer/#%E4%B8%BA%E5%95%A5%E6%88%91%E7%9A%84%E7%BD%91%E9%A1%B5%E4%B8%8A%E7%9A%84%E5%88%87%E5%9B%BE%E6%B2%A1%E6%9C%89%E4%B8%8B%E8%BD%BD%E6%8C%89%E9%92%AE
