### ISSUE TITLE
希望在多page文件里选择一个page里面的frame时，在生成的离线包里没有没选择的page

### ISSUE THREAD

**Issue by aimechan** [leadream/heron-handoff#69]
我file里的page是不同日期修改版本，当一个文件有多个page时，选择其中一个page的frame进行操作，在生成的离线包里依旧有没选择的page，就有点尴尬。谢谢。

**Comment by leadream** [comment]
@aimechan 可以通过邮件提供更详细的信息吗？可以复制一个文件邀请我去试一下，邮箱如下：
leadream4@gmail.com

**Comment by leadream** [comment]
Fixed.
