### ISSUE TITLE
Can't export on MacOS

### ISSUE THREAD

**Issue by ziairshad** [leadream/heron-handoff#71]
Hi, thanks for the great plugin but for some reason I can't export from MacOS as it always get stuck on "Processing CSS" step and never moves. Is someone else having the same who was able to resolve it? Thanks
<img width="320" alt="Screen Shot 2022-05-26 at 11 51 55 AM" src="https://user-images.githubusercontent.com/8416356/170443825-fff596b5-8ccc-4ef5-8e81-2a242bc22451.png">

**Comment by leadream** [comment]
@ziairshad It's a bug I guess. I'll try to fix it tonight.

**Comment by buja0** [comment]
I have the same issue at the moment..😭
